# Uncommment this to replace the rest of the file when you want to debug stuff in CI


#name: Run Debug
#
#on:
#  push:
#  pull_request:
#  workflow_dispatch:
#
#jobs:
#  debug:
#    runs-on: ubuntu-latest
##    runs-on: windows-latest
#    steps:
#      - uses: actions/checkout@v4
#        with: { fetch-depth: 1 }
#
#      - run: "echo temurin:11 > .mill-jvm-version"
#
#      - uses: sbt/setup-sbt@v1
#
#
#      - run:  ./mill 'integration.migrating[init].local.server.testOnly' mill.integration.MillInitSbtGatlingTests
#



# We run full CI on push builds to main and on all pull requests
#
# To maximize bug-catching changes while keeping CI times reasonable, we run
# all tests on Linux, scattered between Java 11/17, except for one job run
# on MacOS instead and a subset of jobs also run on windows


name: Run Tests

on:
  push:
    branches-ignore:
      - '**-patch-**'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:

# cancel older runs of a pull request;
# this will not cancel anything for normal git pushes
concurrency:
  # * For runs on other repos, always use the `ref_name` so each branch only can have one concurrent run
  # * For runs on `com-lihaoyi/mill`, use `head_ref` to allow one concurrent run per PR, but `run_id` to
  #   allow multiple concurrent runs in master
  group: cancel-old-pr-runs-${{ github.workflow }}-${{ (github.repository != 'com-lihaoyi/mill' && github.ref_name) || (github.head_ref || github.run_id) }}
  cancel-in-progress: true

jobs:
  build-windows:
    if: (github.event.action == 'ready_for_review') || (github.event.pull_request.draft == false)
    uses: ./.github/workflows/pre-build.yml
    with:
      os: windows-latest
      shell: powershell

  windows:
    needs: build-windows
    strategy:
      fail-fast: false
      matrix:
        include:
          # just run a subset of examples/ on Windows, because for some reason running
          # the whole suite can take hours on windows v.s. half an hour on linux
          #
          # * One job unit tests,
          # * One job each for local/packaged/native tests
          # * At least one job for each of fork/server tests, and example/integration tests
          - java-version: 11
            millargs: '"{main,scalalib,bsp}.__.test"'
            install-sbt: false

    uses: ./.github/workflows/post-build-selective.yml
    with:
      os: windows-latest
      java-version: ${{ matrix.java-version }}
      millargs: ${{ matrix.millargs }}
      # Provide a shorter coursier archive folder to avoid hitting path-length bugs when
      # running the graal native image binary on windows
      coursierarchive: "C:/coursier-arc"
      shell: powershell
      install-sbt: ${{ matrix.install-sbt }}
